config/routes.rb
Rails.application.routes.draw do
  #resources :users
  #resources :sheets
  # resources :infosettings
  #resources :settings
  # resources :choices
  #resources :operations
  # resources :msystems
  # resources :osystems
  # resources :preparations
  # resources :expeople
  # resources :actions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :operations do
  #   put :sort
  # end
  get 'layouts/loading'=>'layouts#loading'


  #以下より旧版の
  get 'list' => "home#list"

  #User関連
  post "login" => "users#login"
  post 'logout' => "users#logout"
  #get 'systemoperation/login' => "user#login_form"
  get 'login' => "users#login_form"
  get "signup" => "users#new"
  get "users/index" =>"users#index"
  post "users/create"=>"users#create"
  get "users/:emp_code" => "users#show"
  get "users/:emp_code/edit" => "users#edit"
  post "users/:id/destroy" => "users#destroy"
  post "users/:emp_code/update" => "users#update"
  post "users/import" => "usesr#import"
  resources :user do
    collection { post :import }
  end




  #Sheet関連
  #作成
  get 'sheets/new'=>"sheets#new"
  get 'sheets/gexnew'=>"sheets#gexnew"
  get 'sheets/infosetnew'=>"sheets#infosetnew"
  post 'sheets/create' =>"sheets#create"
  post "sheets/:id/person_set"=>"sheets#person_set"
  post "sheets/:id/person_delete"=>"sheets#person_delete"
  get 'sheets/bulk_new' =>"sheets#bulk_new"
  post 'sheets/bulk_create' =>"sheets#bulk_create"
  get 'sheets/bulk_setindex' =>"sheets#bulk_setindex"
  post 'sheets/:id/bulk_set' =>"sheets#bulk_set"
  post 'sheets/:id/div_set' =>"sheets#div_set"
  post 'sheets/csv_exp' =>"sheets#csv_exp"
  post 'sheets/:id/remarks_update' =>"sheets#remarks_update"
  post 'sheets/:id/remarks_do' =>"sheets#remarks_do"
  post 'sheets/:id/remarks_undo' =>"sheets#remarks_undo"

  #参照
  get 'sheets/index' => "sheets#index"
  get 'sheets/setindex' => "sheets#setindex"
  get 'sheets/doneindex' => "sheets#doneindex"
  get 'sheets/:id/edit' => "sheets#edit"
  get 'sheets/:id/setedit' => "sheets#setedit"
  get 'sheets/:id/infoedit' => "sheets#infoedit"
  get 'sheets/:id/infosetedit' => "sheets#infosetedit"
  get 'sheets/:id' => "sheets#show"
  get 'sheets/:id/info' => "sheets#info"
  get 'sheets/:id/gex' => "sheets#gex"
  get 'sheets/:id/gex_set' => "sheets#gex_set"
  post 'sheets/gex_inp/:id/:col1//:col2/:col3' => "sheets#gex_inp"
  post 'sheets/:id/update' => "sheets#update"
  #入力
  post "sheets/do/:id/:act_id" => "sheets#do"
  post "sheets/undo/:id/:act_id" => "sheets#undo"
  post "sheets/set/:id/:prp_id" => "sheets#set"
  post "sheets/unset/:id/:prp_id" => "sheets#unset"
  post 'sheets/:id/set' =>"sheets#set"
  post 'sheets/:id/done' =>"sheets#done"
  post "sheets/:id/destroy" => "sheets#destroy"
  post "sheets/destroy_old_sheets" => "sheets#destroy_old_sheets"
  delete "sheets/:id/destroy" => "sheets#destroy"
  post "sheets/:id/setdestroy" => "sheets#setdestroy"
  post 'sheets/:id/cancel' => "sheets#cancel"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Operation関連
  get "operations/index" => "operations#index"
  get "operations/infoindex" => "operations#infoindex"
  get "operations/new" => "operations#new"
  get "operations/infonew" => "operations#infonew"
  get "operations/:id" => "operations#edit"
  get "operations/:id/infoedit" => "operations#infoedit"
  post "operations/:id/set_num" => "operations#set_num"
  post "operations/create" => "operations#create"
  post "operations/infocreate" => "operations#infocreate"
  post "operations/:id/update" => "operations#update"
  post "operations/:id/infoupdate" => "operations#infoupdate"
  post "operations/:id/destroy" => "operations#destroy"
  post "operations/:id/infodestroy" => "operations#infodestroy"
  post "operations/:id/valid" => "operations#valid"
  post "operations/import" => "operations#import"
  post "operations/opreset"=>"operations#opreset"
  #ソート用
  
  #post "operations/:id/sort" => "operations#sort"

  #Setting関連
  get "settings/index" => "settings#index"
  get "settings/new/:op_code" => "settings#new"
  get "settings/infonew/:op_code" => "settings#infonew"
  get "settings/edit/:id/:op_code" => "settings#edit"
  get "settings/infoedit/:id/:op_code" => "settings#infoedit"
  post"settings/create" => "settings#create"
  post"settings/infocreate" => "settings#infocreate"
  post"settings/:id/update" => "settings#update"
  post"settings/:id/infoupdate" => "settings#infoupdate"
  post"settings/:id/destroy" => "settings#destroy"
  post"settings/:id/valid" => "settings#valid"
  post"settings/import" => "settings#import"
  

  #Choices関連
  get "choices/index" => "choices#index"
  get "choices/setindex" => "choices#setindex"
  get "choices/new/:op_code" => "choices#new"
  get "choices/setnew/:set_code" => "choices#setnew"
  get "choices/edit/:op_code" => "choices#edit"
  get "choices/setedit/:set_code" => "choices#setedit"
  post "choices/create" => "choices#create"
  post "choices/setcreate" => "choices#setcreate"
  post "choices/:id/update" => "choices#update"
  post "choices/:id/setupdate" => "choices#setupdate"
  post "choices/:id/valid" => "choices#valid"
  post "choices/:id/destroy" => "choices#destroy"
  post "choices/:id/setdestroy" => "choices#setdestroy"
  post "choices/import" => "choices#import"

  #Osystem関連
  get "osystems/index" => "osystems#index"
  get "osystems/new" => "osystems#new"
  get "osystems/:id" => "osystems#edit"
  post "osystems/create" => "osystems#create"
  post "osystems/:id/update" => "osystems#update"
  post "osystems/:id/destroy" => "osystems#destroy"
  post "osystems/:id/validate" => "osystems#validate"
  post "osystems/:id/indvalidate" => "osystems#invalidate"
  post "osystems/import" => "osystems#import"

  #Msystem関連
  get "msystems/index" => "msystems#index"
  get "msystems/new" => "msystems#new"
  get "msystems/:id" => "msystems#edit"
  get "msystems/:id/show" => "msystems#show"
  post "msystems/create" => "msystems#create"
  post "msystems/:id/update" => "msystems#update"
  post "msystems/:id/destroy" => "msystems#destroy"
  post "msystems/:id/validate" => "msystems#validate"
  post "msystems/:id/indvalidate" => "msystems#invalidate"
  post "msystems/import" => "msystems#import"

  #Expepople関連
  get "expeople/:id" => "expeople#edit"
  get "expeople/:id/show" => "expeople#show"
  post "expeople/:id/create" => "expeople#create"
  post "expeople/:id/:exp_id/update" => "expeople#update"
  post "expeople/:id/:exp_id/destroy" => "expeople#destroy"
  post "expeople/:id/do" => "expeople#do"
  post "expeople/:id/undo" => "expeople#undo"
  post "expeople/import" => "expeople#import"

end

app/models/choice.rb
class Choice < ApplicationRecord
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  #before_action :set_choice, only: %i[ show edit update destroy ]
  #非ログイン状態ではログイン画面に強制遷移する
  before_action :authenticate_user

  # GET /choices or /choices.json
  def index
    @choices = Choice.all
  end

  # GET /choices/1 or /choices/1.json
  def show
  end

  # GET /choices/new
  def new
    @choice = Choice.new
  end

  # GET /choices/1/edit
  def edit
    @choices = Choice.where(op_code: params[:op_code])
    @choice = Choice.new
    @operation = Operation.find_by(op_code: params[:op_code])
  end

  def setedit
    @choices = Choice.where(set_code: params[:set_code])
    @choice = Choice.new
    @setting = Setting.find_by(set_code: params[:set_code])
    @operation = Operation.find_by(op_code: @setting.op_code)
  end

  # POST /choices or /choices.json
  def create
    @operation = Operation.find_by(op_code: params[:op_code])
    @choice = Choice.new(
      choice_name: params[:choice_name],
      op_code: params[:op_code]
    )
    #必須記述入力項目のエラーチェック
    if params[:choice_name] == nil || params[:choice_name] == "" 
      check = "1"
    end

    if check != "1"
        if @choice.save
          flash[:notice] = "選択肢登録が完了しました"
          redirect_to(controller: :choices, action: :edit, id: @choice.id, op_code: @operation.op_code)
        else
          render("choices/edit")
        end
    else
        flash[:notice] = "選択肢が未入力です"
        render("choices/edit")
    end
  end

  def setcreate
    @setting = Setting.find_by(set_code: params[:set_code])
    @choice = Choice.new(
      choice_name: params[:choice_name],
      set_code: params[:set_code]
    )
    #必須記述入力項目のエラーチェック
    if params[:choice_name] == nil || params[:choice_name] == "" 
      check = "1"
    end

    if check != "1"
        if @choice.save
          flash[:notice] = "選択肢登録が完了しました"
          redirect_to(controller: :choices, action: :setedit, id: @choice.id, set_code: @setting.set_code)
        else
          render("choices/edit")
        end
    else
        flash[:notice] = "選択肢が未入力です"
        render("choices/edit")
    end
  end

  # PATCH/PUT /choices/1 or /choices/1.json
  def update
    @operation = Operation.find_by(op_code: params[:op_code])
    @choice = Choice.find_by(id: params[:id])
      @choice.choice_name =  params[:choice_name]
      @choice.op_code = params[:op_code]

    #必須記述入力項目のエラーチェック
    if params[:choice_name] == nil || params[:choice_name] == "" 
      check = "1"
    end

    if check != "1"
        if @choice.save
          flash[:notice] = "選択肢登録が完了しました"
          redirect_to(controller: :choices, action: :edit, id: @choice.id, op_code: @operation.op_code)
        else
          render("choices/edit")
        end
    else
        flash[:notice] = "選択肢が未入力です"
        render("choices/edit")
    end
  end

  def setupdate
    @setting = Setting.find_by(set_code: params[:set_code])
    @choice = Choice.find_by(id: params[:id])
      @choice.choice_name =  params[:choice_name]
      @choice.set_code = params[:set_code]

    #必須記述入力項目のエラーチェック
    if params[:choice_name] == nil || params[:choice_name] == "" 
      check = "1"
    end

    if check != "1"
        if @choice.save
          flash[:notice] = "選択肢登録が完了しました"
          redirect_to(controller: :choices, action: :setedit, id: @choice.id, set_code: @setting.set_code)
        else
          render("choices/edit")
        end
    else
        flash[:notice] = "選択肢が未入力です"
        render("choices/edit")
    end
  end

  # DELETE /choices/1 or /choices/1.json
  def destroy
    @choice = Choice.find_by(id: params[:id])
    @choice.destroy
    @operation = Operation.find_by(op_code: params[:op_code])
    redirect_to(controller: :choices, action: :edit, id: @choice.id, op_code: @operation.op_code)
  end

  def setdestroy
    @choice = Choice.find_by(id: params[:id])
    @choice.destroy
    @setting = Setting.find_by(set_code: params[:set_code])
    redirect_to(controller: :choices, action: :setedit, id: @choice.id, set_code: @setting.set_code)
  end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_choice
  #     @choice = Choice.find(params[:id])
  #   end

  #   # Only allow a list of trusted parameters through.
  #   def choice_params
  #     params.fetch(:choice, {})
  #   end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/views/choices/_form.html.erb
<%= form_with(model: choice) do |form| %>
  <% if choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
        <% choice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing Choice</h1>

<div class="main posts-new">
    <div class="container">
        <h1 class="form-heading">選択肢編集</h1>
        <%@operation.op_code%>
        <div class="form-top">
            <div class="form-body">
                <div class="form-error">
                </div>
                <!--親オペレーションの表示-->
                <%if @operation%>
                    <%= link_to(@operation.op_name, {controller: :operations, action: :edit, id: @operation.id})%>
                <%end%>
            </div>
        </div>
        <div class="form">
            <div class="form-body">
            <% @operation.errors.full_messages.each do |message| %>
                <div class="form-error">
                <%= message %>
                </div>
            <% end %>

            <!--選択肢(テキスト)-->
            <p class="item-name">選択肢</p>
            <br>
            
            <%= form_tag({controller: :choices, action: :create, op_code: @operation.op_code}, {id: "sub",multipart: true}) do %>
            <input type="text" name="choice_name" value="<%= @choice.choice_name %>">
            <input type="submit" value="新規作成">
            <%end%>
            <br>
            <br>
            
            <% @choices.each do |choice| %>
                <%= form_tag({controller: :choices, action: :update, op_code: @operation.op_code,id: choice.id }, {id: "sub",multipart: true}) do %>
                        <input type="text" name="choice_name" value="<%= choice.choice_name %>">
                        <%= link_to("削除", {controller: :choices, action: :destroy, op_code: @operation.op_code,id: choice.id }, {method: "post"})%>
                        <%
=begin%>
 <%= link_to("削除", {controller: :sheets, action: :destroy ,id: @sheet.id }, {method: "post"})%>  
<%
=end%>
                        <input type="submit" value="更新"> 
                <%end%>
                <br>
            <%end%>
            </div>
        </div>
    </div>
</div>

app/views/choices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Choices</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @choices.each do |choice| %>
      <tr>
        <td><%= link_to 'Show', choice %></td>
        <td><%= link_to 'Edit', edit_choice_path(choice) %></td>
        <td><%= link_to 'Destroy', choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Choice', new_choice_path %>

app/views/choices/new.html.erb
<h1>New Choice</h1>

<%= render 'form', choice: @choice %>

<%= link_to 'Back', choices_path %>

app/views/choices/setedit.html.erb
<h1>Editing Choice</h1>

<div class="main posts-new">
    <div class="container">
        <h1 class="form-heading">選択肢編集</h1>
        <%@setting.set_code%>
        <div class="form-top">
            <div class="form-body">
                <div class="form-error">
                </div>
                <!--親オペレーションの表示-->
                <%if @setting%>
                    <%= link_to(@setting.set_name, {controller: :settings, action: :edit, id: @setting.id,op_code: @setting.op_code})%>
                <%end%>
            </div>
        </div>
        <div class="form">
            <div class="form-body">
            <% @setting.errors.full_messages.each do |message| %>
                <div class="form-error">
                <%= message %>
                </div>
            <% end %>

            <!--選択肢(テキスト)-->
            <p class="item-name">選択肢</p>
            <br>
            
            <%= form_tag({controller: :choices, action: :setcreate, set_code: @setting.set_code}, {multipart: true}) do %>
            <input type="text" name="choice_name" value="<%= @choice.choice_name %>">
            <input type="submit" value="新規作成">
            <%end%>
            <br>
            <br>
            
            <% @choices.each do |choice| %>
                <%= form_tag({controller: :choices, action: :setupdate, set_code: @setting.set_code,id: choice.id }, {multipart: true}) do %>
                        <input type="text" name="choice_name" value="<%= choice.choice_name %>">
                        <%= link_to("削除", {controller: :choices, action: :setdestroy, set_code: @setting.set_code,id: choice.id }, {method: "post"})%>
                        <%
=begin%>
 <%= link_to("削除", {controller: :sheets, action: :destroy ,id: @sheet.id }, {method: "post"})%>  
<%
=end%>
                        <input type="submit" value="更新"> 
                <%end%>
                <br>
            <%end%>
            </div>
        </div>
    </div>
</div>

app/views/choices/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_choice_path(@choice) %> |
<%= link_to 'Back', choices_path %>