config/routes.rb
Rails.application.routes.draw do
  #resources :users
  #resources :sheets
  # resources :infosettings
  #resources :settings
  # resources :choices
  #resources :operations
  # resources :msystems
  # resources :osystems
  # resources :preparations
  # resources :expeople
  # resources :actions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :operations do
  #   put :sort
  # end
  get 'layouts/loading'=>'layouts#loading'


  #以下より旧版の
  get 'list' => "home#list"

  #User関連
  post "login" => "users#login"
  post 'logout' => "users#logout"
  #get 'systemoperation/login' => "user#login_form"
  get 'login' => "users#login_form"
  get "signup" => "users#new"
  get "users/index" =>"users#index"
  post "users/create"=>"users#create"
  get "users/:emp_code" => "users#show"
  get "users/:emp_code/edit" => "users#edit"
  post "users/:id/destroy" => "users#destroy"
  post "users/:emp_code/update" => "users#update"
  post "users/import" => "usesr#import"
  resources :user do
    collection { post :import }
  end




  #Sheet関連
  #作成
  get 'sheets/new'=>"sheets#new"
  get 'sheets/gexnew'=>"sheets#gexnew"
  get 'sheets/infosetnew'=>"sheets#infosetnew"
  post 'sheets/create' =>"sheets#create"
  post "sheets/:id/person_set"=>"sheets#person_set"
  post "sheets/:id/person_delete"=>"sheets#person_delete"
  get 'sheets/bulk_new' =>"sheets#bulk_new"
  post 'sheets/bulk_create' =>"sheets#bulk_create"
  get 'sheets/bulk_setindex' =>"sheets#bulk_setindex"
  post 'sheets/:id/bulk_set' =>"sheets#bulk_set"
  post 'sheets/:id/div_set' =>"sheets#div_set"
  post 'sheets/csv_exp' =>"sheets#csv_exp"
  post 'sheets/:id/remarks_update' =>"sheets#remarks_update"
  post 'sheets/:id/remarks_do' =>"sheets#remarks_do"
  post 'sheets/:id/remarks_undo' =>"sheets#remarks_undo"

  #参照
  get 'sheets/index' => "sheets#index"
  get 'sheets/setindex' => "sheets#setindex"
  get 'sheets/doneindex' => "sheets#doneindex"
  get 'sheets/:id/edit' => "sheets#edit"
  get 'sheets/:id/setedit' => "sheets#setedit"
  get 'sheets/:id/infoedit' => "sheets#infoedit"
  get 'sheets/:id/infosetedit' => "sheets#infosetedit"
  get 'sheets/:id' => "sheets#show"
  get 'sheets/:id/info' => "sheets#info"
  get 'sheets/:id/gex' => "sheets#gex"
  get 'sheets/:id/gex_set' => "sheets#gex_set"
  post 'sheets/gex_inp/:id/:col1//:col2/:col3' => "sheets#gex_inp"
  post 'sheets/:id/update' => "sheets#update"
  #入力
  post "sheets/do/:id/:act_id" => "sheets#do"
  post "sheets/undo/:id/:act_id" => "sheets#undo"
  post "sheets/set/:id/:prp_id" => "sheets#set"
  post "sheets/unset/:id/:prp_id" => "sheets#unset"
  post 'sheets/:id/set' =>"sheets#set"
  post 'sheets/:id/done' =>"sheets#done"
  post "sheets/:id/destroy" => "sheets#destroy"
  post "sheets/destroy_old_sheets" => "sheets#destroy_old_sheets"
  delete "sheets/:id/destroy" => "sheets#destroy"
  post "sheets/:id/setdestroy" => "sheets#setdestroy"
  post 'sheets/:id/cancel' => "sheets#cancel"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Operation関連
  get "operations/index" => "operations#index"
  get "operations/infoindex" => "operations#infoindex"
  get "operations/new" => "operations#new"
  get "operations/infonew" => "operations#infonew"
  get "operations/:id" => "operations#edit"
  get "operations/:id/infoedit" => "operations#infoedit"
  post "operations/:id/set_num" => "operations#set_num"
  post "operations/create" => "operations#create"
  post "operations/infocreate" => "operations#infocreate"
  post "operations/:id/update" => "operations#update"
  post "operations/:id/infoupdate" => "operations#infoupdate"
  post "operations/:id/destroy" => "operations#destroy"
  post "operations/:id/infodestroy" => "operations#infodestroy"
  post "operations/:id/valid" => "operations#valid"
  post "operations/import" => "operations#import"
  post "operations/opreset"=>"operations#opreset"
  #ソート用
  
  #post "operations/:id/sort" => "operations#sort"

  #Setting関連
  get "settings/index" => "settings#index"
  get "settings/new/:op_code" => "settings#new"
  get "settings/infonew/:op_code" => "settings#infonew"
  get "settings/edit/:id/:op_code" => "settings#edit"
  get "settings/infoedit/:id/:op_code" => "settings#infoedit"
  post"settings/create" => "settings#create"
  post"settings/infocreate" => "settings#infocreate"
  post"settings/:id/update" => "settings#update"
  post"settings/:id/infoupdate" => "settings#infoupdate"
  post"settings/:id/destroy" => "settings#destroy"
  post"settings/:id/valid" => "settings#valid"
  post"settings/import" => "settings#import"
  

  #Choices関連
  get "choices/index" => "choices#index"
  get "choices/setindex" => "choices#setindex"
  get "choices/new/:op_code" => "choices#new"
  get "choices/setnew/:set_code" => "choices#setnew"
  get "choices/edit/:op_code" => "choices#edit"
  get "choices/setedit/:set_code" => "choices#setedit"
  post "choices/create" => "choices#create"
  post "choices/setcreate" => "choices#setcreate"
  post "choices/:id/update" => "choices#update"
  post "choices/:id/setupdate" => "choices#setupdate"
  post "choices/:id/valid" => "choices#valid"
  post "choices/:id/destroy" => "choices#destroy"
  post "choices/:id/setdestroy" => "choices#setdestroy"
  post "choices/import" => "choices#import"

  #Osystem関連
  get "osystems/index" => "osystems#index"
  get "osystems/new" => "osystems#new"
  get "osystems/:id" => "osystems#edit"
  post "osystems/create" => "osystems#create"
  post "osystems/:id/update" => "osystems#update"
  post "osystems/:id/destroy" => "osystems#destroy"
  post "osystems/:id/validate" => "osystems#validate"
  post "osystems/:id/indvalidate" => "osystems#invalidate"
  post "osystems/import" => "osystems#import"

  #Msystem関連
  get "msystems/index" => "msystems#index"
  get "msystems/new" => "msystems#new"
  get "msystems/:id" => "msystems#edit"
  get "msystems/:id/show" => "msystems#show"
  post "msystems/create" => "msystems#create"
  post "msystems/:id/update" => "msystems#update"
  post "msystems/:id/destroy" => "msystems#destroy"
  post "msystems/:id/validate" => "msystems#validate"
  post "msystems/:id/indvalidate" => "msystems#invalidate"
  post "msystems/import" => "msystems#import"

  #Expepople関連
  get "expeople/:id" => "expeople#edit"
  get "expeople/:id/show" => "expeople#show"
  post "expeople/:id/create" => "expeople#create"
  post "expeople/:id/:exp_id/update" => "expeople#update"
  post "expeople/:id/:exp_id/destroy" => "expeople#destroy"
  post "expeople/:id/do" => "expeople#do"
  post "expeople/:id/undo" => "expeople#undo"
  post "expeople/import" => "expeople#import"

end

app/models/setting.rb
class Setting < ApplicationRecord
    belongs_to :operation
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  #非ログイン状態ではログイン画面に強制遷移する
  before_action :authenticate_user


  # GET /settings or /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1 or /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
    @operation = Operation.find_by(op_code: params[:op_code])
    @msystems = Msystem.where(valid_flg: "1")
  end

  def infonew
    @setting = Setting.new
    @operation = Operation.find_by(op_code: params[:op_code])
    @msystems = Msystem.where(valid_flg: "1")
  end

  # GET /settings/1/edit
  def edit
    @setting = Setting.find_by(id: params[:id])
    @operation = Operation.find_by(op_code: params[:op_code])
    @choices = Choice.where(set_code: @setting.set_code)
    @choice = Choice.new
    @msystems = Msystem.all
    @msystem = Msystem.find_by(msys_code: @setting.msys_code)
  end

  def infoedit
    @setting = Setting.find_by(id: params[:id])
    @operation = Operation.find_by(op_code: params[:op_code])
    @choices = Choice.where(set_code: @setting.set_code)
    @choice = Choice.new
    @msystems = Msystem.all
    @msystem = Msystem.find_by(msys_code: @setting.msys_code)
  end

  def update
    @setting = Setting.find_by(id: params[:id])
    @operation = Operation.find_by(op_code: params[:op_code])
    @msystems = Msystem.all
    @msystem = Msystem.find_by(msys_code: params[:msystem][:msys_code])

    @setting.set_name = params[:set_name]
    @setting.set_code = @setting.id
    @setting.set_num = params[:set_num]
    @setting.set_type = params[:set_type]
    @setting.op_code = @operation.op_code
    @setting.msys_code = @msystem.msys_code
    @setting.must_flg = params[:must_flg]
    @setting.set_div = params[:set_div]
    @setting.date_div = params[:date_div]
    @setting.command = params[:command]
    @setting.caution = params[:caution]
    # @setting.branch_code = params[:branch_code]
    # @setting.branch_cont = params[:branch_cont]
    @setting.sbranch_code = params[:sbranch_code]
    @setting.sbranch_cont = params[:sbranch_cont]

    #必須記述入力項目のエラーチェック
    if params[:set_name] == nil || params[:set_name] == ""
      check = "1"
    elsif params[:set_num] == nil || params[:set_num] == ""
      check = "1"
    elsif params[:msystem][:msys_code] == nil || params[:msystem][:msys_code] == ""
      check = "1"
    end

    #選択肢フラグのチェック
    # if @setting.set_type == "7"
    #   @setting.choice_flg = "1"
    # else
    #   @setting.choice_flg = nil
    # end

    if check != "1"
        if @setting.save
        flash[:notice] = "設定登録が完了しました"
        redirect_to({controller: :settings, action: :edit, id: @setting.id, op_code: @operation.op_code} )
        else
        render("settings/edit")
        end
    else
        flash[:notice] = "未入力の必須項目があります"
        render("settings/edit")
    end
  end

  def infoupdate
    @setting = Setting.find_by(id: params[:id])
    @operation = Operation.find_by(op_code: params[:op_code])
    @msystems = Msystem.all
    #@msystem = Msystem.find_by(msys_code: params[:msystem][:msys_code])

    @setting.default_value =  params[:default_value]

    #必須記述入力項目のエラーチェック
    if params[:set_name] == nil || params[:set_name] == ""
      check = "1"
    end

    if check != "1"
        if @setting.save
        flash[:notice] = "設定登録が完了しました"
        redirect_to({controller: :settings, action: :infoedit, id: @setting.id, op_code: @operation.op_code} )
        else
        render("settings/infoedit")
        end
    else
        flash[:notice] = "未入力の必須項目があります"
        render("settings/ifnoedit")
    end
  end

  # POST /settings or /settings.json
  def create
    @operation = Operation.find_by(op_code: params[:op_code])
    @msystems = Msystem.all
    @setting = Setting.new(
      set_name: params[:set_name],
      #set_code: params[:set_code],
      set_num: params[:set_num],
      set_type: params[:set_type],
      op_code: @operation.op_code,
      operation_id: @operation.id,
      msys_code: params[:msys_code],
      must_flg: params[:must_flg],
      set_div: params[:set_div],
      date_div: params[:date_div],
      command: params[:command],
      caution: params[:caution],
      branch_code: "",
      branch_cont: "",
      sbranch_code: params[:sbranch_code],
      sbranch_cont: params[:sbranch_cont]
  )
  #必須記述入力項目のエラーチェック
  if params[:set_name] == nil || params[:set_name] == ""
    check = "1"
  elsif params[:set_num] == nil || params[:set_num] == ""
    check = "1"
  elsif params[:msys_code] == nil || params[:msys_code] == ""
    check = "1"
  end

  #重複エラーチェック
  # setting_c = Setting.find_by(set_code: params[:set_code])
  # if setting_c
  #   flash[:notice] = "重複したコードでは登録出来ません"
  #   render("settings/new")
  #   return
  # end

  if check != "1"
      #選択肢のチェック(選択肢フラグが立っている場合はそのまま選択肢編集画面へ)
    if @setting.set_type == "7"
      # @setting.choice_flg = "1"
      @setting.save
      @setting.set_code = @setting.id
      @setting.save
      redirect_to(controller: :choices, action: :setedit,set_code: @setting.set_code)
    else
      if @setting.save
      @setting.set_code = @setting.id
      @setting.save
      flash[:notice] = "設定登録が完了しました"
      redirect_to({controller: :operations, action: :edit, id: @operation.id} )
      else
      render("settings/new")
      end
    end
  else
      flash[:notice] = "未入力の必須項目があります"
      render("settings/new")
  end
  end

  def infocreate
    @operation = Operation.find_by(op_code: params[:op_code])
    @msystems = Msystem.all
    @setting = Setting.new(
      set_name: params[:set_name],
      set_type: "6",
      op_code: @operation.op_code,
      must_flg: "",
      default_value: params[:default_value],

  )
  #必須記述入力項目のエラーチェック
  if params[:set_name] == nil || params[:set_name] == ""
    check = "1"
  end

  if check != "1"
      #選択肢のチェック(選択肢フラグが立っている場合はそのまま選択肢編集画面へ)
    if @setting.set_type == "7"
      # @setting.choice_flg = "1"
      @setting.save
      @setting.set_code = @setting.id
      @setting.save
      redirect_to(controller: :choices, action: :setedit,set_code: @setting.set_code)
    else
      if @setting.save
        @setting.set_code = @setting.id
        @setting.save
      flash[:notice] = "設定登録が完了しました"
      redirect_to({controller: :operations, action: :infoedit, id: @operation.id} )
      else
      render("settings/infonew")
      end
    end
  else
      flash[:notice] = "未入力の必須項目があります"
      render("settings/infonew")
  end
  end

  def destroy
    @setting = Setting.find_by(id: params[:id])
    @operation = Operation.find_by(op_code: @setting.op_code)
    @choices = Choice.where(set_code: @setting.set_code)
    @choice = Choice.new
    @choices.destroy_all
    @msystems = Msystem.all
    if @setting.destroy
      redirect_to({controller: :operations, action: :edit, id: @operation.id} )
    else
      render("settings/edit")
    end
    #@msystem = Msystem.find_by(msys_code: @setting.msys_code)
  end
  private

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_with(model: setting) do |form| %>
  <% if setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
        <% setting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>
<!--ココから旧-->

<div class="main posts-new">
    <div class="container">
        
        <%= link_to("戻る", {controller: :operations, action: :edit, id: @operation.id})%>
        <h1 class="form-heading">編集</h1>
        <%= form_tag({controller: :settings, action: :update, op_code: @operation.op_code ,id: @setting.id}, {id: "sub",multipart: true}) do %>
        <div class="form">
            <div class="form-body">
            <% @setting.errors.full_messages.each do |message| %>
                <div class="form-error">
                <%= message %>
                </div>
            <% end %>
            <!--関連オペレーションを表示-->
            <%if @operation%>
            <div class="division">
                <ul>
                <li>
                <%= link_to(@operation.op_name, {controller: :operations, action: :edit, id: @operation.id})%>
                </li>
                </ul>
            </div>
            <%end%>
            <br>

            <!--設定コード(テキスト)-->
            <p class="item-name">設定コード</p><p class="ness">*</p>
            <br>
            <input type="text" name="set_code" value="<%= @setting.set_code %>" readonly="readonly">
            <br>
            <br> 

            <!--設定名(テキスト)-->
            <p class="item-name">設定名</p><p class="ness">*</p>
            <br>
            <input type="text" name="set_name" value="<%= @setting.set_name %>">
            <br>
            <br>
            <!--並び順(数値)-->
            <p class="item-name">並び順</p><p class="ness">*</p>
            <br>
            <input type="number" name="set_num" value="<%= @setting.set_num %>">
            <br>
            <br>
            <!--入力属性(コンボボックス)-->
            <p class="item-name">入力属性</p><p class="ness">*</p>
            <br>
            <select name="set_type">
                <% if @setting.set_type == "0" || @setting.set_type == nil %>
                    <option value="0" selected>打刻のみ</option>
                <%else%>
                    <option value="0" >打刻のみ</option>
                <%end%>

                <% if @setting.set_type == "1" %>
                    <option value="1" selected >数値(整数)</option>
                <%else%>
                    <option value="1">数値(整数)</option>
                <%end%>

                <% if @setting.set_type == "2" %>
                    <option value="2" selected>数値(小数)</option>
                <%else%>
                    <option value="2">数値(小数)</option>
                <%end%>

                <% if @setting.set_type == "3" %>
                    <option value="3" selected>テキスト</option>
                <%else%>
                    <option value="3">テキスト</option> 
                <%end%>

                <% if @setting.set_type == "4" %>
                    <option value="4" selected>日付</option>
                <%else%>
                    <option value="4">日付</option>
                <%end%>

                <% if @setting.set_type == "5" %>
                    <option value="5" selected>時刻</option>
                <%else%>
                    <option value="5">時刻</option>
                <%end%>

                <% if @setting.set_type == "6" %>
                    <option value="6" selected>テキストエリア</option>
                <%else%>
                    <option value="6">テキストエリア</option>
                <%end%>

                <% if @setting.set_type == "7" %>
                    <option value="7" selected>選択肢</option>
                <%else%>
                    <option value="7">選択肢</option>
                <%end%>
            </select>
            <br>
            <br>

            <!--対象当番区分(コンボボックス)-->
            <p class="item-name">設定値区分</p><p class="ness">*</p>
            <br>
            <select name="set_div">
                <% if @setting.set_div == "0"  %>
                    <option value="0" selected>その他</option>
                <%else%>
                    <option value="0" >その他</option>
                <%end%>

                <% if @setting.set_div == "1" || @setting.set_div == nil%>
                    <option value="1" selected >処理日付</option>
                <%else%>
                    <option value="1">処理日付</option>
                <%end%>

                <% if @setting.set_div == "2" %>
                    <option value="2" selected>開始日</option>
                <%else%>
                    <option value="2">開始日</option>
                <%end%>

                <% if @setting.set_div == "3" %>
                    <option value="3" selected>終了日</option>
                <%else%>
                    <option value="3">終了日</option>
                <%end%>

                <% if @setting.set_div == "4" %>
                    <option value="4" selected>年</option>
                <%else%>
                    <option value="4">年</option>
                <%end%>

                <% if @setting.set_div == "5" %>
                    <option value="5" selected>月</option>
                <%else%>
                    <option value="5">月</option>
                <%end%>

                <% if @setting.set_div == "6" %>
                    <option value="6" selected>日</option>
                <%else%>
                    <option value="6">日</option>
                <%end%>

                <% if @setting.set_div == "7" %>
                    <option value="7" selected>期</option>
                <%else%>
                    <option value="7">期</option>
                <%end%>
            </select>
            <br>
            <br>

            <!--管理システムコード(テキスト)--><!--本番は選択式-->
            <p class="item-name">管理システムコード</p><p class="ness">*</p>
            <br>
            <%if @msystem%>
            <%= collection_select(:msystem,:msys_code, @msystems, :msys_code, :msys_name,:prompt => "#{@msystem.msys_name}") %>
            <%else%>
            <%= collection_select(:msystem,:msys_code, @msystems, :msys_code, :msys_name,:prompt => "選択してください") %>
            <%end%>
            <br>
            <br>

            <!--必須フラグ(チェックボックス))-->
            <p class="item-name">必須フラグ</p><p class="ness">*</p>
            <br>
            <div class="form-checkbox">
                <% if @setting.must_flg == "1" || @setting.must_flg == nil %>
                    <input name="must_flg" type="hidden" value="0" />
                    <input class="custom-checkbox" type="checkbox" value="1" name="must_flg" checked="checked"/>
                <%else%>
                    <input name="must_flg" type="hidden" value="0" />
                    <input class="custom-checkbox" type="checkbox" value="1" name="must_flg" />
                <%end%>
            </div>
            <br>

            
            <!--自動設定日付区分(コンボボックス)-->
            <p class="item-name">自動設定日付</p><p class="ness">*</p>
            <br>
            <select name="date_div">
                <% if @setting.date_div == "00" || @setting.date_div == nil %>
                    <option value="00" selected>初期値無し</option>
                <%else%>
                    <option value="00">初期値無し</option>
                <%end%>
                <% if @setting.date_div == "0" %>
                    <option value="0" selected>当日</option>
                <%else%>
                    <option value="0" >当日</option>
                <%end%>

                <% if @setting.date_div == "1" %>
                    <option value="1" selected >翌営業日</option>
                <%else%>
                    <option value="1">翌営業日</option>
                <%end%>

                <% if @setting.date_div == "2" %>
                    <option value="2" selected>翌々営業日</option>
                <%else%>
                    <option value="2">翌々営業日</option>
                <%end%>

                <% if @setting.date_div == "3" %>
                    <option value="3" selected>前営業日</option>
                <%else%>
                    <option value="3">前営業日</option>
                <%end%>

                <% if @setting.date_div == "4" %>
                    <option value="4" selected>当月20日</option>
                <%else%>
                    <option value="4">当月20日</option>
                <%end%>

                <% if @setting.date_div == "5" %>
                    <option value="5" selected>月初</option>
                <%else%>
                    <option value="5">月初</option>
                <%end%>

                <% if @setting.date_div == "6" %>
                    <option value="6" selected>翌営業日(土曜含む)</option>
                <%else%>
                    <option value="6">翌営業日(土曜含む)</option>
                <%end%>
            </select>
            <br>
            <br>
            
            <!--コマンド(テキスト)-->
            <br>
            <p class="item-name">コマンド</p>
            <br>
            <input type="text" name="command" value="<%= @setting.command %>">
            <br>
            <br>

            <!--注意事項(テキスト)-->
            <p class="item-name">注意事項</p>
            <br>
            <input type="text" name="caution" value="<%= @setting.caution %>">
            <br>
            <br>
            
            <!--選択肢枠(テキスト)-->
            <% if @setting.set_type == "7" %>
                <p class="item-name">選択肢</p>
                <% @choices.each do |choice| %>
                        <div class = "settings-list">
                            <input type="text" name="choice_name" value="<%= choice.choice_name %>" readonly = "readonly">
                        </div>
                <%end%>
                <%= link_to("選択肢編集", controller: :choices, action: :setedit,set_code: @setting.set_code) %> 
                <br>
                <br>
                <input type="text" name="caution" value="<%= @setting.caution %>">
                <br>
                <br>
            <%end%>
<%
=begin%>
 
            <!--表示キー項目コード(テキスト)-->
            <p class="item-name">表示キー項目コード</p>
            <br>
            <input type="text" name="branch_code" value="<%= @setting.branch_code %>">
            <br>
            <br>

            <!--表示キー項目内容(テキスト)-->
            <p class="item-name">表示キー項目内容</p>
            <br>
            <input type="text" name="branch_cont" value="<%= @setting.branch_cont %>">
            <br>
            <br> 
<%
=end%>

            <!--表示設定キー項目コード(テキスト)-->
            <p class="item-name">表示設定キー項目コード</p>
            <br>
            <input type="text" name="sbranch_code" value="<%= @setting.sbranch_code %>">
            <%@branch_set = Setting.find_by(set_code: @setting.sbranch_code)%>
            <%if @branch_set%>
                結果：<%=@branch_set.set_name%>
            <%end%>
            <br>
            <br>

            <!--表示設定キー項目内容(テキスト)-->
            <p class="item-name">表示設定キー項目内容</p>
            <br>
            <input type="text" name="sbranch_cont" value="<%= @setting.sbranch_cont %>">
            <br>
            <br>
            <%if @branch_set%>
                <%@choices = Choice.where(set_code: @branch_set.set_code)%>
                <%if @choices[0]%>
                候補：
                    <%@choices.each do |choice|%>
                    <%=choice.choice_name%>
                    <%end%>
                <%end%>
            <%end%>
            <input type="submit" value="更新">
            </div>
        </div>
        <% end %>
        <%= link_to("削除", {controller: :settings, action: :destroy,id: @setting.id }, {method: "post"})%>
    </div>
</div>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Settings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/infoedit.html.erb
<h1>Editing Setting</h1>
<!--ココから旧-->

<div class="main posts-new">
    <div class="container">
        <%= link_to("戻る", {controller: :operations, action: :infoedit, id: @operation.id})%>
        <h1 class="form-heading">編集</h1>
        <%= form_tag({controller: :settings, action: :infoupdate, op_code: @operation.op_code ,id: @setting.id}, {id: "sub",multipart: true}) do %>
        <div class="form">
            <div class="form-body">
            <% @setting.errors.full_messages.each do |message| %>
                <div class="form-error">
                <%= message %>
                </div>
            <% end %>
            <!--関連オペレーションを表示-->
            <%if @operation%>
            <%= link_to(@operation.op_name, {controller: :operations, action: :edit, id: @operation.id})%>
            <%end%>
            <br>
            <!--設定コード(テキスト)-->
            <p class="item-name">設定コード</p><p class="ness">*</p>
            <br>
            <input type="text" name="set_code" value="<%= @setting.set_code %>" readonly="readonly">
            <br>
            <br>
            <!--設定名(テキスト)-->
            <p class="item-name">設定名</p><p class="ness">*</p>
            <br>
            <input type="text" name="set_name" value="<%= @setting.set_name %>">
            <br>
            <br>

            <!--初期値(テキスト)-->
            <p class="item-name">初期値</p><p class="ness">*</p>
            <br>
            <textarea name="default_value"><%if @setting.default_value %><%=@setting.default_value %><%end%></textarea>
            <br>


            <input type="submit" value="作成">
            </div>
        </div>
        <% end %>
        <%= link_to("削除", {controller: :settings, action: :destroy,id: @setting.id }, {method: "post"})%>
    </div>
</div>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>