config/routes.rb
Rails.application.routes.draw do
  #resources :users
  #resources :sheets
  # resources :infosettings
  #resources :settings
  # resources :choices
  #resources :operations
  # resources :msystems
  # resources :osystems
  # resources :preparations
  # resources :expeople
  # resources :actions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :operations do
  #   put :sort
  # end
  get 'layouts/loading'=>'layouts#loading'


  #以下より旧版の
  get 'list' => "home#list"

  #User関連
  post "login" => "users#login"
  post 'logout' => "users#logout"
  #get 'systemoperation/login' => "user#login_form"
  get 'login' => "users#login_form"
  get "signup" => "users#new"
  get "users/index" =>"users#index"
  post "users/create"=>"users#create"
  get "users/:emp_code" => "users#show"
  get "users/:emp_code/edit" => "users#edit"
  post "users/:id/destroy" => "users#destroy"
  post "users/:emp_code/update" => "users#update"
  post "users/import" => "usesr#import"
  resources :user do
    collection { post :import }
  end




  #Sheet関連
  #作成
  get 'sheets/new'=>"sheets#new"
  get 'sheets/gexnew'=>"sheets#gexnew"
  get 'sheets/infosetnew'=>"sheets#infosetnew"
  post 'sheets/create' =>"sheets#create"
  post "sheets/:id/person_set"=>"sheets#person_set"
  post "sheets/:id/person_delete"=>"sheets#person_delete"
  get 'sheets/bulk_new' =>"sheets#bulk_new"
  post 'sheets/bulk_create' =>"sheets#bulk_create"
  get 'sheets/bulk_setindex' =>"sheets#bulk_setindex"
  post 'sheets/:id/bulk_set' =>"sheets#bulk_set"
  post 'sheets/:id/div_set' =>"sheets#div_set"
  post 'sheets/csv_exp' =>"sheets#csv_exp"
  post 'sheets/:id/remarks_update' =>"sheets#remarks_update"
  post 'sheets/:id/remarks_do' =>"sheets#remarks_do"
  post 'sheets/:id/remarks_undo' =>"sheets#remarks_undo"

  #参照
  get 'sheets/index' => "sheets#index"
  get 'sheets/setindex' => "sheets#setindex"
  get 'sheets/doneindex' => "sheets#doneindex"
  get 'sheets/:id/edit' => "sheets#edit"
  get 'sheets/:id/setedit' => "sheets#setedit"
  get 'sheets/:id/infoedit' => "sheets#infoedit"
  get 'sheets/:id/infosetedit' => "sheets#infosetedit"
  get 'sheets/:id' => "sheets#show"
  get 'sheets/:id/info' => "sheets#info"
  get 'sheets/:id/gex' => "sheets#gex"
  get 'sheets/:id/gex_set' => "sheets#gex_set"
  post 'sheets/gex_inp/:id/:col1//:col2/:col3' => "sheets#gex_inp"
  post 'sheets/:id/update' => "sheets#update"
  #入力
  post "sheets/do/:id/:act_id" => "sheets#do"
  post "sheets/undo/:id/:act_id" => "sheets#undo"
  post "sheets/set/:id/:prp_id" => "sheets#set"
  post "sheets/unset/:id/:prp_id" => "sheets#unset"
  post 'sheets/:id/set' =>"sheets#set"
  post 'sheets/:id/done' =>"sheets#done"
  post "sheets/:id/destroy" => "sheets#destroy"
  post "sheets/destroy_old_sheets" => "sheets#destroy_old_sheets"
  delete "sheets/:id/destroy" => "sheets#destroy"
  post "sheets/:id/setdestroy" => "sheets#setdestroy"
  post 'sheets/:id/cancel' => "sheets#cancel"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Operation関連
  get "operations/index" => "operations#index"
  get "operations/infoindex" => "operations#infoindex"
  get "operations/new" => "operations#new"
  get "operations/infonew" => "operations#infonew"
  get "operations/:id" => "operations#edit"
  get "operations/:id/infoedit" => "operations#infoedit"
  post "operations/:id/set_num" => "operations#set_num"
  post "operations/create" => "operations#create"
  post "operations/infocreate" => "operations#infocreate"
  post "operations/:id/update" => "operations#update"
  post "operations/:id/infoupdate" => "operations#infoupdate"
  post "operations/:id/destroy" => "operations#destroy"
  post "operations/:id/infodestroy" => "operations#infodestroy"
  post "operations/:id/valid" => "operations#valid"
  post "operations/import" => "operations#import"
  post "operations/opreset"=>"operations#opreset"
  #ソート用
  
  #post "operations/:id/sort" => "operations#sort"

  #Setting関連
  get "settings/index" => "settings#index"
  get "settings/new/:op_code" => "settings#new"
  get "settings/infonew/:op_code" => "settings#infonew"
  get "settings/edit/:id/:op_code" => "settings#edit"
  get "settings/infoedit/:id/:op_code" => "settings#infoedit"
  post"settings/create" => "settings#create"
  post"settings/infocreate" => "settings#infocreate"
  post"settings/:id/update" => "settings#update"
  post"settings/:id/infoupdate" => "settings#infoupdate"
  post"settings/:id/destroy" => "settings#destroy"
  post"settings/:id/valid" => "settings#valid"
  post"settings/import" => "settings#import"
  

  #Choices関連
  get "choices/index" => "choices#index"
  get "choices/setindex" => "choices#setindex"
  get "choices/new/:op_code" => "choices#new"
  get "choices/setnew/:set_code" => "choices#setnew"
  get "choices/edit/:op_code" => "choices#edit"
  get "choices/setedit/:set_code" => "choices#setedit"
  post "choices/create" => "choices#create"
  post "choices/setcreate" => "choices#setcreate"
  post "choices/:id/update" => "choices#update"
  post "choices/:id/setupdate" => "choices#setupdate"
  post "choices/:id/valid" => "choices#valid"
  post "choices/:id/destroy" => "choices#destroy"
  post "choices/:id/setdestroy" => "choices#setdestroy"
  post "choices/import" => "choices#import"

  #Osystem関連
  get "osystems/index" => "osystems#index"
  get "osystems/new" => "osystems#new"
  get "osystems/:id" => "osystems#edit"
  post "osystems/create" => "osystems#create"
  post "osystems/:id/update" => "osystems#update"
  post "osystems/:id/destroy" => "osystems#destroy"
  post "osystems/:id/validate" => "osystems#validate"
  post "osystems/:id/indvalidate" => "osystems#invalidate"
  post "osystems/import" => "osystems#import"

  #Msystem関連
  get "msystems/index" => "msystems#index"
  get "msystems/new" => "msystems#new"
  get "msystems/:id" => "msystems#edit"
  get "msystems/:id/show" => "msystems#show"
  post "msystems/create" => "msystems#create"
  post "msystems/:id/update" => "msystems#update"
  post "msystems/:id/destroy" => "msystems#destroy"
  post "msystems/:id/validate" => "msystems#validate"
  post "msystems/:id/indvalidate" => "msystems#invalidate"
  post "msystems/import" => "msystems#import"

  #Expepople関連
  get "expeople/:id" => "expeople#edit"
  get "expeople/:id/show" => "expeople#show"
  post "expeople/:id/create" => "expeople#create"
  post "expeople/:id/:exp_id/update" => "expeople#update"
  post "expeople/:id/:exp_id/destroy" => "expeople#destroy"
  post "expeople/:id/do" => "expeople#do"
  post "expeople/:id/undo" => "expeople#undo"
  post "expeople/import" => "expeople#import"

end

app/models/msystem.rb
class Msystem < ApplicationRecord
end

app/controllers/msystems_controller.rb
class MsystemsController < ApplicationController
  before_action :set_msystem, only: %i[ show edit update destroy ]
  #非ログイン状態ではログイン画面に強制遷移する
  before_action :authenticate_user

  # GET /msystems or /msystems.json
  def index
    #通常パラメータの場合は、有効な操作システムを表示
    if params[:vaild_flg] == "1"
      @msystems = Msystem.where(valid_flg: "1").order(osys_name: :asc)
      @valid_flg = params[:valid_flg]
    #無効パラメータの場合は、無効な操作システムを表示
    elsif params[:valid_flg] == "0"
      @msystems = Msystem.where(valid_flg: "0").order(osys_name: :asc)
      @valid_flg = params[:valid_flg]
    else
      @msystems = Msystem.where(valid_flg: "1").order(osys_name: :asc)
      @valid_flg = params[:valid_flg]
    end
  end

  # GET /msystems/1 or /msystems/1.json
  # def show
  # end

  # GET /msystems/new
  def new
    @msystem = Msystem.new
  end

  # GET /msystems/1/edit
  def edit
  end

  # POST /msystems or /msystems.json
  def create
    @msystem = Msystem.new(msystem_params)
    #@msystem.msys_code = params[:msys_code]
    @msystem.msys_name = params[:msys_name]
    @msystem.valid_flg = "1"
    #重複エラーチェック
    msystem_c = Msystem.find_by(msys_name: params[:msys_name])
    if msystem_c
        flash[:notice] = "既に存在しています"
        render("msystems/new")
        return
    elsif params[:msys_name]==""
      flash[:notice] = "入力して下さい"
        render("msystems/new")
        return
    end
    if @msystem.save
        @msystem.msys_code = @msystem.id
        @msystem.save
        flash[:notice] = "管理SYS登録が完了しました"
        redirect_to(msystems_index_path)
      else
        render("msystems/new")
      end
  end

  # PATCH/PUT /msystems/1 or /msystems/1.json
  def update
    @msystem = Msystem.find_by(id: params[:id])
    @msystem.msys_code = @msystem.id
    @msystem.msys_name = params[:msys_name]

    if @msystem.save
        flash[:notice] = "管理SYS登録が更新しました"
        redirect_to(controller: :msystems, action: :edit,id: @msystem.id)
      else
        render("msystems/edit")
      end
  end

  #無効化
  def invalidate
    @msystem = Msystem.find_by(id: params[:id])
    @msystem.valid_flg = "0"
    @msystem.save

    flash[:notice] = "操作SYSを無効化しました"
    redirect_to msystems_index_path(valid_flg: "0")
  end

  #有効化
  def validate
    @msystem = Msystem.find_by(id: params[:id])
    @msystem.valid_flg = "1"
    @msystem.save

    flash[:notice] = "操作SYSを無効化しました"
    redirect_to msystems_index_path(valid_flg: "1")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_msystem
      @msystem = Msystem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def msystem_params
      params.fetch(:msystem, {})
    end
end

app/helpers/msystems_helper.rb
module MsystemsHelper
end

app/views/msystems/_form.html.erb
<%= form_with(model: msystem) do |form| %>
  <% if msystem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(msystem.errors.count, "error") %> prohibited this msystem from being saved:</h2>

      <ul>
        <% msystem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/msystems/edit.html.erb
<h1>Edit Opssytem</h1>


<!--ココから旧-->

<div class="main posts-new">
    <div class="container">
    <%= link_to '戻る', {controller: :msystems, action: :index} %>
        <h1 class="form-heading">管理システム編集</h1>
        <%= form_tag({controller: :msystems, action: :update, id: @msystem.id}, {id: "sub",multipart: true}) do %>
        <div class="form">
            <div class="form-body">
            <% @msystem.errors.full_messages.each do |message| %>
                <div class="form-error">
                <%= message %>
                </div>
            <% end %>
            <!--有効/無効ステータスで変更の可否分岐-->
            <%if @msystem.valid_flg == "1"%>
            <!--オペレーション名(テキスト)-->
                <p class="item-name">管理システム名</p><p class="ness">*</p>
                <br>
                <input type="text" name="msys_name" value="<%= @msystem.msys_name %>">
                <br>
                <br>
                <input type="submit" value="作成">
            <%else%>
                <p class="item-name">管理システム名</p><p class="ness">*</p>
                <br>
                <input type="text" name="msys_name" value="<%= @msystem.msys_name %>" readonly>
                <br>
                <br>
            <%end%>
        </div>
        <% end %>
        
    </div>
        <!--有効/無効ステータスで有効/無効化-->
        <div class= "link-btn">
        <%if @msystem.valid_flg == "1"%>
            <%= link_to("無効化", {controller: :msystems, action: :invalidate,id: @msystem.id }, {method: "post"})%>
        <%else%>
            <%= link_to("有効化", {controller: :msystems, action: :validate,id: @msystem.id }, {method: "post"})%>
        <%end%>
</div>

app/views/msystems/index.html.erb
<p id="notice"><%= notice %></p>

<h1></h1>
<br>

<%= link_to 'New opsystem', msystems_new_path %>

<div class="main users-index">
  <div class="container-set">
    <h1 class="form-heading">管理システム一覧</h1>
    <%if @valid_flg != "0"%>
    <div class="right">
      <div class= "link-btn">
        <%= link_to '新規作成', msystems_new_path %>
      </div>
    </div>
    <%end%>
    <div class="search-btn">
    <%= link_to"有効", msystems_index_path(valid_flg: "1") %>
    <%= link_to"無効", msystems_index_path(valid_flg: "0") %>
    </div>
    <% @msystems.each do |msystem| %>
          <div class="users-index-item">
              <%= link_to(msystem.msys_name, controller: :msystems, action: :edit, id: msystem.id) %>
          </div>
        <% end %> 
  </div>
</div>

app/views/msystems/new.html.erb
<h1>New Opssytem</h1>


<!--ココから旧-->

<div class="main posts-new">
    <div class="container">
    <%= link_to '戻る', {controller: :msystems, action: :index} %>
        <h1 class="form-heading">新規作成</h1>
        <%= form_tag(msystems_create_path,id: "sub") do %>
        <div class="form">
            <div class="form-body">
            <% @msystem.errors.full_messages.each do |message| %>
                <div class="form-error">
                <%= message %>
                </div>
            <% end %>
            <%
=begin%>
 <!--オペレーションコード(テキスト)-->
            <p class="item-name">管理システムコード</p><p class="ness">*</p>
            <br>
            <input type="text" name="msys_code" value="<%= @msystem.msys_code %>">
            <br>
            <br> 
<%
=end%>
            <!--オペレーション名(テキスト)-->
            <p class="item-name">管理システム名</p><p class="ness">*</p>
            <br>
            <input type="text" name="msys_name" value="<%= @msystem.msys_name %>">
            <br>
            <br>
            <input type="submit" value="作成">
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/msystems/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_msystem_path(@msystem) %> |
<%= link_to 'Back', msystems_path %>