config/routes.rb
Rails.application.routes.draw do
  #resources :users
  #resources :sheets
  # resources :infosettings
  #resources :settings
  # resources :choices
  #resources :operations
  # resources :msystems
  # resources :osystems
  # resources :preparations
  # resources :expeople
  # resources :actions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :operations do
  #   put :sort
  # end
  get 'layouts/loading'=>'layouts#loading'


  #以下より旧版の
  get 'list' => "home#list"

  #User関連
  post "login" => "users#login"
  post 'logout' => "users#logout"
  #get 'systemoperation/login' => "user#login_form"
  get 'login' => "users#login_form"
  get "signup" => "users#new"
  get "users/index" =>"users#index"
  post "users/create"=>"users#create"
  get "users/:emp_code" => "users#show"
  get "users/:emp_code/edit" => "users#edit"
  post "users/:id/destroy" => "users#destroy"
  post "users/:emp_code/update" => "users#update"
  post "users/import" => "usesr#import"
  resources :user do
    collection { post :import }
  end




  #Sheet関連
  #作成
  get 'sheets/new'=>"sheets#new"
  get 'sheets/gexnew'=>"sheets#gexnew"
  get 'sheets/infosetnew'=>"sheets#infosetnew"
  post 'sheets/create' =>"sheets#create"
  post "sheets/:id/person_set"=>"sheets#person_set"
  post "sheets/:id/person_delete"=>"sheets#person_delete"
  get 'sheets/bulk_new' =>"sheets#bulk_new"
  post 'sheets/bulk_create' =>"sheets#bulk_create"
  get 'sheets/bulk_setindex' =>"sheets#bulk_setindex"
  post 'sheets/:id/bulk_set' =>"sheets#bulk_set"
  post 'sheets/:id/div_set' =>"sheets#div_set"
  post 'sheets/csv_exp' =>"sheets#csv_exp"
  post 'sheets/:id/remarks_update' =>"sheets#remarks_update"
  post 'sheets/:id/remarks_do' =>"sheets#remarks_do"
  post 'sheets/:id/remarks_undo' =>"sheets#remarks_undo"

  #参照
  get 'sheets/index' => "sheets#index"
  get 'sheets/setindex' => "sheets#setindex"
  get 'sheets/doneindex' => "sheets#doneindex"
  get 'sheets/:id/edit' => "sheets#edit"
  get 'sheets/:id/setedit' => "sheets#setedit"
  get 'sheets/:id/infoedit' => "sheets#infoedit"
  get 'sheets/:id/infosetedit' => "sheets#infosetedit"
  get 'sheets/:id' => "sheets#show"
  get 'sheets/:id/info' => "sheets#info"
  get 'sheets/:id/gex' => "sheets#gex"
  get 'sheets/:id/gex_set' => "sheets#gex_set"
  post 'sheets/gex_inp/:id/:col1//:col2/:col3' => "sheets#gex_inp"
  post 'sheets/:id/update' => "sheets#update"
  #入力
  post "sheets/do/:id/:act_id" => "sheets#do"
  post "sheets/undo/:id/:act_id" => "sheets#undo"
  post "sheets/set/:id/:prp_id" => "sheets#set"
  post "sheets/unset/:id/:prp_id" => "sheets#unset"
  post 'sheets/:id/set' =>"sheets#set"
  post 'sheets/:id/done' =>"sheets#done"
  post "sheets/:id/destroy" => "sheets#destroy"
  post "sheets/destroy_old_sheets" => "sheets#destroy_old_sheets"
  delete "sheets/:id/destroy" => "sheets#destroy"
  post "sheets/:id/setdestroy" => "sheets#setdestroy"
  post 'sheets/:id/cancel' => "sheets#cancel"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Operation関連
  get "operations/index" => "operations#index"
  get "operations/infoindex" => "operations#infoindex"
  get "operations/new" => "operations#new"
  get "operations/infonew" => "operations#infonew"
  get "operations/:id" => "operations#edit"
  get "operations/:id/infoedit" => "operations#infoedit"
  post "operations/:id/set_num" => "operations#set_num"
  post "operations/create" => "operations#create"
  post "operations/infocreate" => "operations#infocreate"
  post "operations/:id/update" => "operations#update"
  post "operations/:id/infoupdate" => "operations#infoupdate"
  post "operations/:id/destroy" => "operations#destroy"
  post "operations/:id/infodestroy" => "operations#infodestroy"
  post "operations/:id/valid" => "operations#valid"
  post "operations/import" => "operations#import"
  post "operations/opreset"=>"operations#opreset"
  #ソート用
  
  #post "operations/:id/sort" => "operations#sort"

  #Setting関連
  get "settings/index" => "settings#index"
  get "settings/new/:op_code" => "settings#new"
  get "settings/infonew/:op_code" => "settings#infonew"
  get "settings/edit/:id/:op_code" => "settings#edit"
  get "settings/infoedit/:id/:op_code" => "settings#infoedit"
  post"settings/create" => "settings#create"
  post"settings/infocreate" => "settings#infocreate"
  post"settings/:id/update" => "settings#update"
  post"settings/:id/infoupdate" => "settings#infoupdate"
  post"settings/:id/destroy" => "settings#destroy"
  post"settings/:id/valid" => "settings#valid"
  post"settings/import" => "settings#import"
  

  #Choices関連
  get "choices/index" => "choices#index"
  get "choices/setindex" => "choices#setindex"
  get "choices/new/:op_code" => "choices#new"
  get "choices/setnew/:set_code" => "choices#setnew"
  get "choices/edit/:op_code" => "choices#edit"
  get "choices/setedit/:set_code" => "choices#setedit"
  post "choices/create" => "choices#create"
  post "choices/setcreate" => "choices#setcreate"
  post "choices/:id/update" => "choices#update"
  post "choices/:id/setupdate" => "choices#setupdate"
  post "choices/:id/valid" => "choices#valid"
  post "choices/:id/destroy" => "choices#destroy"
  post "choices/:id/setdestroy" => "choices#setdestroy"
  post "choices/import" => "choices#import"

  #Osystem関連
  get "osystems/index" => "osystems#index"
  get "osystems/new" => "osystems#new"
  get "osystems/:id" => "osystems#edit"
  post "osystems/create" => "osystems#create"
  post "osystems/:id/update" => "osystems#update"
  post "osystems/:id/destroy" => "osystems#destroy"
  post "osystems/:id/validate" => "osystems#validate"
  post "osystems/:id/indvalidate" => "osystems#invalidate"
  post "osystems/import" => "osystems#import"

  #Msystem関連
  get "msystems/index" => "msystems#index"
  get "msystems/new" => "msystems#new"
  get "msystems/:id" => "msystems#edit"
  get "msystems/:id/show" => "msystems#show"
  post "msystems/create" => "msystems#create"
  post "msystems/:id/update" => "msystems#update"
  post "msystems/:id/destroy" => "msystems#destroy"
  post "msystems/:id/validate" => "msystems#validate"
  post "msystems/:id/indvalidate" => "msystems#invalidate"
  post "msystems/import" => "msystems#import"

  #Expepople関連
  get "expeople/:id" => "expeople#edit"
  get "expeople/:id/show" => "expeople#show"
  post "expeople/:id/create" => "expeople#create"
  post "expeople/:id/:exp_id/update" => "expeople#update"
  post "expeople/:id/:exp_id/destroy" => "expeople#destroy"
  post "expeople/:id/do" => "expeople#do"
  post "expeople/:id/undo" => "expeople#undo"
  post "expeople/import" => "expeople#import"

end

app/models/operation.rb
class Operation < ApplicationRecord
    #順番ソート用
    include RankedModel
    ranks :row_order
    has_many :settings
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: %i[ show edit update destroy ]
  #非ログイン状態ではログイン画面に強制遷移する
  before_action :authenticate_user

  # GET /operations or /operations.json
  def index
    
    
    #締日区分選択がある場合
    if params[:div] || @div 
      #binding.break
      @operations = Operation.where.not(params[:div].to_sym  => "0").order(op_num: :asc)
      #当番区分で抽出
      if params[:duty] == nil
        @operations = Operation.where.not(params[:div].to_sym  => "0").order(op_num: :asc)
      elsif params[:duty] != nil 
        @operations = Operation.where(duty_div: params[:duty]).where.not(params[:div].to_sym  => "0").order(op_num: :asc)
      else
        @operations = Operation.where.not(params[:div].to_sym  => "0").order(op_num: :asc)
      end
    #締日区分選択がない場合
    else
      #当番区分で抽出
      if params[:duty] == nil
        @operations = Operation.where.not(duty_div: "4.情報課作業").order(op_num: :asc)
      elsif params[:duty] != nil 
        @operations = Operation.where(duty_div: params[:duty]).where.not(duty_div: "4.情報課作業").order(op_num: :asc)
      else
        @operations = Operation.where.not(duty_div: "4.情報課作業").order(op_num: :asc)
      end
    end

    #検索用変数保存
    @duty_div = params[:duty]
    @div = params[:div]

    @divs = ["inv","cf","ac","bigm","fare","mnth","mnxt","tmp"] 
    @div_names = ["請求","締","会締","月初","運締","月次","月翌","臨時"]
    #最終行取得用
    @operations_all = Operation.where.not(duty_div: "4.情報課作業").order(op_num: :asc)
    @operation_last = @operations_all.last
  end

  def infoindex
    @operations = Operation.where(duty_div: "4.情報課作業").order(op_num: :asc)
    #@sheets = Sheet.where(set_flg: "1",done_flg: nil).order(duty_date: :asc).paginate(page: params[:page], per_page: 10)
  end

  # GET /operations/1 or /operations/1.json
  def show
  end

  #順番セット用
  def set_num
    #変更対象のOPを取得
    @operation = Operation.find_by(id: params[:id])
    #該当OPを除くOP
    @operations = Operation.where.not(duty_div: "4.情報課作業").and(Operation.where.not(id: params[:id])).order(op_num: :asc)
    #最終番号
    @operation_last = @operations.last
    @last_num = @operation_last.op_num
    @last_num = @last_num.to_i
    #移動元番号
    @from_num = @operation.op_num
    @from_num = @from_num.to_i
    #移動先番号
    @to_num = params[:num]
    @to_num = @to_num.to_i

    #開始位置が0の場合は移動先番号を+1
    if @from_num == 0
      @to_num = @to_num +1
    end
    #最終番号の末尾にまずは保存
    @operation.op_num = @last_num + 1

    #該当OPを除く全OPの番号を1~振替
    @count = 1
    @operations.each do |operation|
      operation.op_num = @count
      operation.save
      @count = @count +1
    end

    #該当OPを保存
    @operation.op_num = @to_num
    @operation.save
    #該当OPの移動先以降のOPを取得
    @to_num_query = @to_num -1
    @operations_to = Operation.where("op_num > ?",@to_num_query).where.not(duty_div: "4.情報課作業").and(Operation.where.not(id: @operation.id)).order(op_num: :asc)
    #移動先以降にOPが存在する場合
    if @operations_to[0]
      #移動先OP以降のOPの順を全て繰り上げる
      @count = @to_num
      @operations_to.each do |operation|
        @count = @count + 1
        operation.op_num = @count
        operation.save
      end
    end
    
    flash[:notice] = "#{@operation.op_name}を#{@to_num}へ移動しました"
    redirect_to(operations_index_path)
  end

  # GET /operations/new
  def new
    @operation = Operation.new
    #最終行レコードを取得
    @operation_last = Operation.last(1)
    @choice = Choice.new
    @osystems = Osystem.where(valid_flg: "1").order(osys_name: :asc)
    
  end

  #情報課作業
  def infonew
    @operation = Operation.new
    #最終行レコードを取得
    @operation_last = Operation.last(1)
    @choice = Choice.new
    @osystems = Osystem.where(valid_flg: "1")
  end


  #編集用取得
  def edit
    @operation = Operation.find_by(id: params[:id])
    @settings = Setting.where(op_code: @operation.op_code)
    @choices = Choice.where(op_code: @operation.op_code)
    @choice = Choice.new
    @osystems = Osystem.all.order(osys_name: :asc)
    @osystem = Osystem.find_by(osys_code: @operation.osys_code)
  end

    #情報課作業編集用取得
    def infoedit
      @operation = Operation.find_by(id: params[:id])
      @settings = Setting.where(op_code: @operation.op_code)
      @choices = Choice.where(op_code: @operation.op_code)
      @choice = Choice.new
      @osystems = Osystem.all
      @osystem = Osystem.find_by(osys_code: @operation.osys_code)
    end

  #更新
  def update
    @operation = Operation.find_by(id: params[:id])
    @settings = Setting.where(op_code: @operation.op_code)
    @choices = Choice.where(op_code: @operation.op_code)
    @choice = Choice.new
    @osystems = Osystem.all
    @osystem = Osystem.find_by(osys_code: params[:osystem][:osys_code]) 
    if @osystem == nil
      @osystem = Osystem.new
    end
    

    @operation.op_name = params[:op_name]
    @operation.op_num = @operation.op_num
    @operation.op_type = params[:op_type]
    @operation.duty_div = params[:duty_div]
    #@operation.op_div = params[:op_div]
    @operation.osys_code = @osystem.osys_code
    @operation.must_flg = params[:must_flg]
    @operation.inv_div = params[:inv_div]
    @operation.cf_div = params[:cf_div]
    @operation.ac_div = params[:ac_div]
    @operation.bigm_div = params[:bigm_div]
    @operation.fare_div = params[:fare_div]
    @operation.mnth_div = params[:mnth_div]
    @operation.mnxt_div = params[:mnxt_div]
    @operation.gex_div = params[:gex_div]
    @operation.tmp_div = params[:tmp_div]
    @operation.ex_div = "0"
    @operation.command = params[:command]
    @operation.caution = params[:caution]
    @operation.branch_code = params[:branch_code]
    @operation.branch_cont = params[:branch_cont]
    @operation.sbranch_code = params[:sbranch_code]
    @operation.sbranch_cont = params[:sbranch_cont]

    #選択肢フラグのチェック
    # if @operation.op_type == "7"
    #   @operation.choice_flg = "1"
    # else
    #   @operation.choice_flg = nil
    # end
    
    #必須記述入力項目のエラーチェック
    if params[:op_name] == nil || params[:op_name] == "" 
      check = "1"
    elsif params[:op_code] == nil || params[:op_code] == ""
      check = "1"
    elsif params[:osystem][:osys_code] == nil || params[:osystem][:osys_code] == ""
      check = "1"
    end

    if check != "1"
        if @operation.save
        flash[:notice] = "オペレーション更新が完了しました"
        redirect_to(operations_index_path)
        else
        render("operations/edit")
        end
    else
        flash[:notice] = "未入力の必須項目があります"
        render("operations/edit")
    end
  end

  #更新
  def infoupdate
    @operation = Operation.find_by(id: params[:id])
    @settings = Setting.where(op_code: @operation.op_code)
    @choices = Choice.where(op_code: @operation.op_code)
    @choice = Choice.new
    @osystems = Osystem.all
    #@osystem = Osystem.find_by(osys_code: params[:osystem][:osys_code]) 
    if @osystem == nil
      @osystem = Osystem.new
    end
    

    @operation.op_name = params[:op_name]
    @operation.op_num = ""
    @operation.duty_div = "4.情報課作業"
    @operation.inv_div = params[:inv_div]
    @operation.cf_div = params[:cf_div]
    @operation.ac_div = params[:ac_div]
    @operation.bigm_div = params[:bigm_div]
    @operation.fare_div = params[:fare_div]
    @operation.mnth_div = params[:mnth_div]
    @operation.mnxt_div = params[:mnxt_div]
    @operation.gex_div = params[:gex_div]
    @operation.tmp_div = params[:tmp_div]
    @operation.ex_div = "0"
    
    #必須記述入力項目のエラーチェック
    if params[:op_name] == nil || params[:op_name] == "" 
      check = "1"
    elsif params[:op_code] == nil || params[:op_code] == ""
      check = "1"
    end

    if check != "1"
        if @operation.save
        flash[:notice] = "オペレーション更新が完了しました"
        redirect_to(operations_infoindex_path)
        else
        render("operations/infoedit")
        end
    else
        flash[:notice] = "未入力の必須項目があります"
        render("operations/infoedit")
    end
  end


  def create
    #--------テスト用
    @operations = Operation.where.not(duty_div: "4.情報課作業").order(op_num: :asc)
    @lastop = @operations.last
    @last_num = @lastop.op_num
    @last_num = @last_num.to_i
    @last_num = @last_num + 1
    #---------
    @operation = Operation.new(
        op_name: params[:op_name],
        # op_code: params[:op_code],
        #テスト用
        #op_num: @last_num,
        #本番用
        op_num:  "0",
        op_type: params[:op_type],
        duty_div: params[:duty_div],
        #op_div: params[:op_div],
        osys_code: params[:osys_code],
        must_flg: params[:must_flg],
        inv_div: params[:inv_div],
        cf_div: params[:cf_div],
        ac_div: params[:ac_div],
        bigm_div: params[:bigm_div],
        fare_div: params[:fare_div],
        mnth_div: params[:mnth_div],
        mnxt_div: params[:mnxt_div],
        gex_div: params[:gex_div],
        tmp_div: params[:tmp_div],
        ex_div: "0",
        command: params[:command],
        caution: params[:caution],
        branch_code: params[:branch_code],
        branch_cont: params[:branch_cont],
        sbranch_code: params[:sbranch_code],
        sbranch_cont: params[:sbranch_cont]
        # if @a_user = User.find_by(emp_code: params[:a_code])
    )
    @choice = Choice.new
    @osystems = Osystem.all

    # #重複エラーチェック
    # operation_c = Operation.find_by(op_code: params[:op_code])
    
    # if operation_c
    #   flash[:notice] = "重複したコードでは登録出来ません"
    #   render("operations/new")
    #   return
    # end

    #必須記述入力項目のエラーチェック
    if params[:op_name] == nil || params[:op_name] == "" 
      check = "1"
    # elsif params[:op_code] == nil || params[:op_code] == ""
    #   check = "1"
    elsif params[:osys_code] == nil || params[:osys_code] == ""
      check = "1"
    end

    
    if check != "1"
        if @operation.save
          #オペコードにidを代入して保存
          @operation.op_code = @operation.id
          @operation.save
        flash[:notice] = "オペレーション登録が完了しました"
        #選択肢のチェック(選択肢フラグが立っている場合はそのまま選択肢編集画面へ)
        if @operation.op_type == "7"
#          @operation.choice_flg = "1"
          @operation.save

app/helpers/operations_helper.rb
module OperationsHelper
end

app/views/operations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Operations</h1>
<br>

<%= link_to 'New Operation', operations_new_path %>

<div class="main users-index">
  <div class="container">
    <div class="link-btn">
    <%= link_to '情報課オペレーション', operations_infoindex_path %>
    </div>
    
    <h1 class="form-heading">オペレーション一覧</h1>
    <%
=begin%>
 <%= link_to("reset", {controller: :operations, action: :opreset }, {method: "post"})%> 
<%
=end%>
    <br>
    <div class="right">
      <div class= "link-btn">
      <%= link_to '新規作成', operations_new_path %>
      </div>
    </div>
    <div class="search-btn">
    <%= link_to"請求当番", operations_index_path(duty: "0.請求当番") %>
    <%= link_to"Ａ当番", operations_index_path(duty: "1.A当番") %>
    <%= link_to"Ｃ当番", operations_index_path(duty: "2.C当番") %>
    <%= link_to"月次当番", operations_index_path(duty: "3.月次当番") %>
    <%= link_to"クリア", operations_index_path(duty: nil) %>
    </div>

    <div class="search-btn">
    <%count = 0%>
    <% @divs.each do |div|%>
      <% div_flg = div + "_div"%>
      <% div_name = @div_names[count]%>
      <%= link_to"#{div_name}", operations_index_path(div: div_flg,duty: @duty_div) %>
      <% count = count + 1%>
    <%end%>
    <%= link_to"クリア", operations_index_path(div: nil,duty: @duty_div) %>

    </div>
<%
=begin%>
 
    <%= form_tag({controller: :operations, action: :import}, multipart: true) do %>
      <%= file_field_tag :file %>
      <%= submit_tag "インポート" %>
    <% end %> 
<%
=end%>
    <!--ソート用ul追加-->
      <ul id="sortable_list">
        
      <% @operations.each do |operation| %>
        <% if operation.duty_div != "4.情報課作業"%>
          <li>  
            <div class="users-index-item">
              <div class="user-left">
                <%= operation.op_num %> 
                
              </div>
              <div class="user-center">
                <%if operation.duty_div%>
                  <p class = "dutys">
                  <%= operation.duty_div.slice(2,20)%>
                  </p>
                  
                <%end%>
                <%= link_to(operation.op_name, controller: :operations, action: :edit, id: operation.id) %>
                <%osystem = Osystem.find_by(osys_code: operation.osys_code)%>
                  <p class= "supplement">
                  <%= osystem.osys_name%>
                  </p>
                <!--関連設定を取得-->
                <%@settings = Setting.where(op_code: operation.op_code)%>
                <% @settings.each do |setting|%>
                  <div class= "command">
                  関連設定：
                  <%= link_to(setting.set_name, controller: :settings, action: :edit, id: setting.id,op_code: operation.op_code) %>
                  </div>
                <%end%>
                <%if operation.op_num == 0%>
                  <div class="caution">
                  並び順を指定して下さい
                  </div>
                <%end%>
                

                
              </div>
              <div class="user-right">
              <!--フラグを表示-->
                <%if operation.inv_div != "0"%>
                  <%if operation.inv_div == "1"%>
                    <div class="add">請求+</div>
                  <%elsif operation.inv_div == "2"%>
                    <div class="dec">請求-</div>
                  <%end%>
                <%end%>
                <%if operation.cf_div != "0"%>
                  <%if operation.cf_div == "1"%>
                    <div class="add">締+</div>
                  <%elsif operation.cf_div == "2"%>
                    <div class="dec">締-</div>
                  <%end%>
                <%end%>
                <%if operation.ac_div != "0"%>
                  <%if operation.ac_div == "1"%>
                    <div class="add">会締+</div>
                  <%elsif operation.ac_div == "2"%>
                    <div class="dec">会締-</div>
                  <%end%>
                <%end%>
                <%if operation.fare_div != "0"%>
                  <%if operation.fare_div == "1"%>
                    <div class="add">運締+</div>
                  <%elsif operation.fare_div == "2"%>
                    <div class="dec">運締-</div>
                  <%end%>
                <%end%>
                <%if operation.bigm_div != "0"%>
                  <%if operation.bigm_div == "1"%>
                    <div class="add">月初+</div>
                  <%elsif operation.bigm_div == "2"%>
                    <div class="dec">月初-</div>
                  <%end%>
                <%end%>
                <%if operation.mnth_div != "0"%>
                  <%if operation.mnth_div == "1"%>
                    <div class="add">月次+</div>
                  <%elsif operation.mnth_div == "2"%>
                    <div class="dec">月次-</div>
                  <%end%>
                <%end%>
                <%if operation.mnxt_div != "0"%>
                  <%if operation.mnxt_div == "1"%>
                    <div class="add">月翌+</div>
                  <%elsif operation.mnxt_div == "2"%>
                    <div class="dec">月翌-</div>
                  <%end%>
                <%end%>
                <%if operation.tmp_div != "0"%>
                  <%if operation.tmp_div == "1"%>
                    <div class="add">臨時+</div>
                  <%elsif operation.tmp_div == "2"%>
                    <div class="dec">臨時-</div>
                  <%end%>
                <%end%>
                </div>

                
                
                

              <% @max = @operation_last.op_num %>
              <div class="user-right-edge">
                  <div class="num">
                  <%= form_tag({controller: :operations, action: :set_num, id: operation.id}, {id: "sub",multipart: true}) do %>
                  <input type="number" name="num" value=""  min= "1" max= <%="#{@max}"%> required >
                  <input type="submit" value="移動">
                  <%end%>
                  </div>
                </div>
            </div>
          </li>
        <%end%>
      <% end %> 
        
      </ul>
  </div>
</div>

app/views/operations/infoindex.html.erb
<p id="notice"><%= notice %></p>

<h1>Operations</h1>
<br>

<div class="main users-index">
  <div class="container">
    <div class="link-btn">
    <%= link_to '通常オペレーション', operations_index_path %>
    </div>
    <h1 class="form-heading">情報課オペレーション一覧</h1>
<%
=begin%>
    <%= form_tag({controller: :operations, action: :import}, multipart: true) do %>
      <%= file_field_tag :file %>
      <%= submit_tag "インポート" %>
    <% end %> 
<%
=end%>
    <div class="link-btn">
    <%= link_to '新規情報課作業', operations_infonew_path %>
    </div>
    <% @operations.each do |operation| %>
          <div class="users-index-item">
            <div class="user-left">
              <%= operation.op_num %> 
            </div>
            <div class="user-center">
              <%= link_to(operation.op_name, controller: :operations, action: :infoedit, id: operation.id) %>
              <!--関連設定を取得-->
                <%@settings = Setting.where(op_code: operation.op_code)%>
                <% @settings.each do |setting|%>
                  <div class= "command">
                  <%= setting.set_name%>
                  </div>
                <%end%>
            </div>
            <div class="user-right">
            <!--フラグを表示-->
              <%if operation.inv_div != "0"%>
                <%if operation.inv_div == "1"%>
                  <div class="add">請求+</div>
                <%elsif operation.inv_div == "2"%>
                  <div class="dec">請求-</div>
                <%end%>
              <%end%>
              <%if operation.cf_div != "0"%>
                <%if operation.cf_div == "1"%>
                  <div class="add">締+</div>
                <%elsif operation.cf_div == "2"%>
                  <div class="dec">締-</div>
                <%end%>
              <%end%>
              <%if operation.ac_div != "0"%>
                <%if operation.ac_div == "1"%>
                  <div class="add">会締+</div>
                <%elsif operation.ac_div == "2"%>
                  <div class="dec">会締-</div>
                <%end%>
              <%end%>
              <%if operation.fare_div != "0"%>
                <%if operation.fare_div == "1"%>
                  <div class="add">運締+</div>
                <%elsif operation.fare_div == "2"%>
                  <div class="dec">運締-</div>
                <%end%>
              <%end%>
              <%if operation.bigm_div != "0"%>
                <%if operation.bigm_div == "1"%>
                  <div class="add">月初+</div>
                <%elsif operation.bigm_div == "2"%>
                  <div class="dec">月初-</div>
                <%end%>
              <%end%>
              <%if operation.mnth_div != "0"%>
                <%if operation.mnth_div == "1"%>
                  <div class="add">月次+</div>
                <%elsif operation.mnth_div == "2"%>
                  <div class="dec">月次-</div>
                <%end%>
              <%end%>
              <%if operation.mnxt_div != "0"%>
                <%if operation.mnxt_div == "1"%>
                  <div class="add">月翌+</div>
                <%elsif operation.mnxt_div == "2"%>
                  <div class="dec">月翌-</div>
                <%end%>
              <%end%>
              <%if operation.tmp_div != "0"%>
                <%if operation.tmp_div == "1"%>
                  <div class="add">臨時+</div>
                <%elsif operation.tmp_div == "2"%>
                  <div class="dec">臨時-</div>
                <%end%>
              <%end%>
              </div>
          </div>
        <% end %> 
  </div>
</div>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_operation_path(@operation) %> |
<%= link_to 'Back', operations_path %>